services:
  ollama:
    container_name: ollama
    image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}
    volumes:
      - ollama:/root/.ollama
    tty: true
    restart: unless-stopped
    pull_policy: always

  open-webui:
    container_name: open-webui
    build:
      context: .
      dockerfile: Dockerfile
      args:
        OLLAMA_BASE_URL: '/ollama'
    restart: unless-stopped
    depends_on:
      - ollama
    ports:
      - "${OPEN_WEBUI_PORT-8081}:8080"
    environment:
      - WEBUI_LANGUAGE=pl
      - WEBUI_NAME=AI-VCCCHAT
      - ENABLE_ADMIN_CHAT_ACCESS=false
      - OLLAMA_BASE_URL=http://ollama:11434
      - WEBUI_SECRET_KEY=
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - open-webui:/app/backend/data
    networks:
      - openwebui_network

  pipelines:
    container_name: pipelines
    image: ghcr.io/open-webui/pipelines:main
    restart: unless-stopped
    ports:
      - "9099:9099"
    volumes:
    - pipelines:/pipelines
    networks:
      - openwebui_network

networks:
  openwebui_network:
    driver: bridge

volumes:
  ollama: {}
  open-webui: {}
  pipelines: {}
